
project_id = "qvarmbhdradfpkegtpgw"

[functions.utility-functions]
verify_jwt = false

[functions.create-get-table-info-function]
verify_jwt = false

[functions.diagnose-connection]
verify_jwt = false
