
project_id = "qvarmbhdradfpkegtpgw"

[functions.utility-functions]
verify_jwt = false

[functions.create-get-table-info-function]
verify_jwt = false

[functions.diagnose-connection]
verify_jwt = false

[functions.retell-webhook]
verify_jwt = false

[functions.retell-webhook-v2]
verify_jwt = false

[functions.cinc-webhook]
verify_jwt = false # Secured by x-cinc-signature

[functions.lead-lookup]
# verify_jwt = true by default

[functions.schedule-callback] # Added this function in a previous step
verify_jwt = false

[functions.cal-webhook] # Newly added function
verify_jwt = false # Public webhook endpoint

[functions.send-sms] # New SMS sending function
verify_jwt = false # Public function for webhook calls

[functions.retell-api-proxy]
verify_jwt = false # Public proxy for Retell API calls
