
project_id = "qvarmbhdradfpkegtpgw"

[functions.utility-functions]
verify_jwt = false

[functions.create-get-table-info-function]
verify_jwt = false

[functions.diagnose-connection]
verify_jwt = false

[functions.retell-webhook]
verify_jwt = false

[functions.retell-webhook-v2]
verify_jwt = false

[functions.retell-webhook-v3]
verify_jwt = false

[functions.cinc-webhook]
verify_jwt = false

[functions.cinc-webhook-v2]
verify_jwt = false

[functions.makecom-callback]
verify_jwt = false

[functions.lead-lookup]
# verify_jwt = true by default

[functions.schedule-callback]
verify_jwt = false

[functions.cal-webhook]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.retell-api-proxy]
verify_jwt = false
