// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvarmbhdradfpkegtpgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2YXJtYmhkcmFkZnBrZWd0cGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzA0MTYsImV4cCI6MjA2MTU0NjQxNn0.nPbIoja88OXjj_0-b_OJzwefRRM1r6T55QljRCxSOuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);